architecture:
  [  # from, module, [arguments]
    [-1, Linear, [~, 128, 0.5]],
    [-1, LinearResidual, [128, 0.5]],
    [-1, LinearResidual, [128, 0.5]],
    [-1, LinearResidual, [128, 0.5]],
    [-1, LinearResidual, [128, 0.5]],
    [-1, LinearResidual, [128, 0.5]],
    [-1, nn.Linear, [128, 1, 0.5]],
    [-1, nn.Sigmoid, []]
  ]

preprocessor:
  log_change_regexes: [
    'Open',
    'High',
    'Low',
    'Close'
  ]
  normalization_regexes: [
    "Volume"
  ]
  rolling_window: ~

hyperparams:
  sample_weight_ratio: 0.9999
  n_epochs: 10
  batch_size: 512
  weight_decay: 0.15