name: Collect, predict and trade

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: cd docker && docker build -t sp2137 . && cd ..

      - name: Run collector
        run: docker run --rm -v $(pwd):/project sp2137 ./venv/bin/python3 ./project/bot.py -DLOG_FILE=project/logs/bot.log -DFILE_LOG_LEVEL=DEBUG collect

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            **/*.log
