name: Collect, predict and trade

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:


jobs:
  Bot:
    runs-on: ubuntu-latest
    env:
      GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        run: cd docker && docker build -t sp2137 . && cd ..

      - name: Run collector
        run: docker run --rm -v $(pwd):/project sp2137 ./venv/bin/python3 ./project/bot.py -DGIT_PASSWORD=${#GIT_PASSWORD} -DLOG_FILE=project/logs/collector.log -DFILE_LOG_LEVEL=DEBUG -DLOCAL_DRIVE_STORE=./project/data -DCACHE_DIR=./project/cache collect --date=latest --name=latest

      - name: Run predictor
        run: docker run --rm -v $(pwd):/project sp2137 ./venv/bin/python3 ./project/bot.py -DGIT_PASSWORD=${#GIT_PASSWORD} -DLOG_FILE=project/logs/predictor.log -DFILE_LOG_LEVEL=DEBUG -DLOCAL_DRIVE_STORE=./project/data -DCACHE_DIR=./project/cache predict --dataset=latest --output=prediction --model=template

      - name: Archive
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: |
            **/*.log
